name: CI

on:
  push:
    branches:
    - master
    - feature/*
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        bazel-version:
          - 3.2.0
          - 3.3.0
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/bazel
          key: bazel-${{ matrix.bazel-version }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ matrix.bazel-version }}-
            bazel-
      - name: Setup build tools
        run: |
          TOOLS_DIR="${HOME}/.cache/tools"
          mkdir -p "${TOOLS_DIR}/bin/"
          curl -Ls -o "${TOOLS_DIR}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
          chmod +x "${TOOLS_DIR}/bin/bazel"
          curl -Ls -o "${TOOLS_DIR}/bin/buildifier" "https://github.com/bazelbuild/buildtools/releases/download/0.29.0/buildifier"
          chmod +x "${TOOLS_DIR}/bin/buildifier"
          curl -Ls -o "${TOOLS_DIR}/bin/kind" "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64"
          chmod +x "${TOOLS_DIR}/bin/kind"
          echo "${TOOLS_DIR}/bin" >> $GITHUB_PATH
      - name: Setup kind cluster
        run: |
          ./create_kind_cluster.sh
      - name: Build
        run: |
          bazel build //...
      - name: Check
        # run downloaded version of buildifier to reduce uncached build times
        # see: bazel run //:buildifier-check
        run: |
          find . -type f \(\
            -name '*.bzl' \
            -o -name '*.sky' \
            -o -name BUILD \
            -o -name BUILD.bazel \
            -o -name WORKSPACE \
            -o -name WORKSPACE.bazel \
          \) | xargs buildifier \
            -mode=check \
            -lint=warn \
            --warnings=-module-docstring,-function-docstring,-function-docstring-header,-function-docstring-args,-function-docstring-return,-print
      - name: Test
        run: |
          bazel test //...
      - name: Build examples
        run: |
          cd examples
          bazel build //...
      - name: Test examples
        run: |
          cd examples
          bazel test //...
      - name: E2E
        run: |
          cd examples
          ./e2e-test.sh
